package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AgentGouv generated by hbm2java
 */
@Entity
@Table(name = "agent_gouv", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AgentGouv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idGouv;
	private Utilisateur utilisateur;
	private String ministere;
	private String direction;
	private String fonction;

	public AgentGouv() {
	}

	public AgentGouv(String id, Utilisateur utilisateur) {
		this.idGouv = id;
		this.utilisateur = utilisateur;
	}

	public AgentGouv(String id, Utilisateur utilisateur, String ministere, String direction, String fonction) {
		this.idGouv = id;
		this.utilisateur = utilisateur;
		this.ministere = ministere;
		this.direction = direction;
		this.fonction = fonction;
	}
	@Id
	@Column(name = "id_gouv", nullable = false, length = 254)
	public String getIdGouv() {
		return this.idGouv;
	}

	public void setIdGouv(String id) {
		this.idGouv = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user")
	@JsonIgnoreProperties({"agentGouvs","comptes"})
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "ministere", length = 254)
	public String getMinistere() {
		return this.ministere;
	}

	public void setMinistere(String ministere) {
		this.ministere = ministere;
	}

	@Column(name = "direction", length = 254)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "fonction", length = 254)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
