package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Annes generated by hbm2java
 */
@Entity
@Table(name = "annes", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Annes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idAnnees;
	private Long annes;
	private Set<StockImportation> stockImportations = new HashSet<StockImportation>(0);
	private Set<StockLocal> stockLocals = new HashSet<StockLocal>(0);

	public Annes() {
	}

	public Annes(Long idAnnees) {
		this.idAnnees = idAnnees;
	}

	/*public Annes(int idAnnees, Long annes, Set stockImportations, Set stockLocals) {
		this.idAnnees = idAnnees;
		this.annes = annes;
		this.stockImportations = stockImportations;
		this.stockLocals = stockLocals;
	}*/
	public Annes(Long idAnnees, Long annes) {
		this.idAnnees = idAnnees;
		this.annes = annes;
		
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_annees", unique = true, nullable = false)
	public Long getIdAnnees() {
		return this.idAnnees;
	}

	public void setIdAnnees(Long idAnnees) {
		this.idAnnees = idAnnees;
	}

	@Column(name = "annes")
	public Long getAnnes() {
		return this.annes;
	}

	public void setAnnes(Long annes) {
		this.annes = annes;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "annes")
	@JsonIgnoreProperties("annes")
	public Set<StockImportation> getStockImportations() {
		return this.stockImportations;
	}

	public void setStockImportations(Set<StockImportation> stockImportations) {
		this.stockImportations = stockImportations;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "annes")
	@JsonIgnoreProperties("annes")
	public Set<StockLocal> getStockLocals() {
		return this.stockLocals;
	}

	public void setStockLocals(Set<StockLocal> stockLocals) {
		this.stockLocals = stockLocals;
	}

}
