package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * DeposerpaddyId generated by hbm2java
 */
@Embeddable
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class DeposerpaddyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUsine;
	private int idUser;
	private int idProd;
	private int idDepot ;

	

	public DeposerpaddyId() {
	}

	public DeposerpaddyId(int idUsine, int idUser, int idProd) {
		this.idUsine = idUsine;
		this.idUser = idUser;
		this.idProd = idProd;
	}
	
	
	@Column(name = "id_depot", nullable = false)
	public int getIdDepot() {
		return idDepot;
	}

	public void setIdDepot(int idDepot) {
		this.idDepot = idDepot;
	}

	@Column(name = "id_usine", nullable = false)
	public int getIdUsine() {
		return this.idUsine;
	}

	public void setIdUsine(int idUsine) {
		this.idUsine = idUsine;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_prod", nullable = false)
	public int getIdProd() {
		return this.idProd;
	}

	public void setIdProd(int idProd) {
		this.idProd = idProd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeposerpaddyId))
			return false;
		DeposerpaddyId castOther = (DeposerpaddyId) other;

		return (this.getIdUsine() == castOther.getIdUsine()) && (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdProd() == castOther.getIdProd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsine();
		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdProd();
		return result;
	}

}
