package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Deposerpaddy generated by hbm2java
 */
@Entity
@Table(name = "deposerpaddy", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Deposerpaddy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DeposerpaddyId id;
	private UsineTransformation usineTransformation;
	private Producteurs producteurs;
	private BigDecimal quantite;
	private String categorie;
	private Date dateDepot;
	private Integer prixKg;
	private Long prixTransKg;

	public Deposerpaddy() {
	}

	public Deposerpaddy(DeposerpaddyId id, UsineTransformation usineTransformation, Producteurs producteurs) {
		this.id = id;
		this.usineTransformation = usineTransformation;
		this.producteurs = producteurs;
	}

	public Deposerpaddy(DeposerpaddyId id, UsineTransformation usineTransformation, Producteurs producteurs,
			BigDecimal quantite, String categorie, Date dateDepot, Integer prixKg, Long prixTransKg) {
		this.id = id;
		this.usineTransformation = usineTransformation;
		this.producteurs = producteurs;
		this.quantite = quantite;
		this.categorie = categorie;
		this.dateDepot = dateDepot;
		this.prixKg = prixKg;
		this.prixTransKg = prixTransKg;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idUsine", column = @Column(name = "id_usine", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
			@AttributeOverride(name = "idProd", column = @Column(name = "id_prod", nullable = false)) })
	public DeposerpaddyId getId() {
		return this.id;
	}

	public void setId(DeposerpaddyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_usine", insertable = false, updatable = false)
	@JsonIgnoreProperties({"deposerpaddies","usineTransformation.stockLocals"})
	public UsineTransformation getUsineTransformation() {
		return this.usineTransformation;
	}

	public void setUsineTransformation(UsineTransformation usineTransformation) {
		this.usineTransformation = usineTransformation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "id_user", referencedColumnName = "id_user", insertable = false, updatable = false),
			@JoinColumn(name = "id_prod", referencedColumnName = "id_prod", insertable = false, updatable = false) })
	@JsonIgnoreProperties("deposerpaddies")
	public Producteurs getProducteurs() {
		return this.producteurs;
	}

	public void setProducteurs(Producteurs producteurs) {
		this.producteurs = producteurs;
	}

	@Column(name = "quantite", precision = 131089, scale = 0)
	public BigDecimal getQuantite() {
		return this.quantite;
	}

	public void setQuantite(BigDecimal quantite) {
		this.quantite = quantite;
	}

	@Column(name = "categorie", length = 254)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_depot", length = 13)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	@Column(name = "prix_kg")
	public Integer getPrixKg() {
		return this.prixKg;
	}

	public void setPrixKg(Integer prixKg) {
		this.prixKg = prixKg;
	}

	@Column(name = "prix_trans_kg")
	public Long getPrixTransKg() {
		return this.prixTransKg;
	}

	public void setPrixTransKg(Long prixTransKg) {
		this.prixTransKg = prixTransKg;
	}

}
