package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Distributeurs generated by hbm2java
 */
@Entity
@Table(name = "distributeurs", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Distributeurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idDist;
	private Utilisateur utilisateur;
	private String ncCommercant;
	private Set<CommandeImport> commandeImports = new HashSet<CommandeImport>(0);
	private Set<CommandeLocal> commandeLocals = new HashSet<CommandeLocal>(0);

	public Distributeurs() {
	}

	public Distributeurs(Long id, Utilisateur utilisateur) {
		this.idDist = id;
		this.utilisateur = utilisateur;
	}

	public Distributeurs(Long id, Utilisateur utilisateur, String ncCommercant, Set<CommandeImport> commandeImports,
			Set<CommandeLocal> commandeLocals) {
		this.idDist = id;
		this.utilisateur = utilisateur;
		this.ncCommercant = ncCommercant;
		this.commandeImports = commandeImports;
		this.commandeLocals = commandeLocals;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_dist", nullable = false)
	public Long getIdDist() {
		return this.idDist;
	}

	public void setIdDist(Long id) {
		this.idDist = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user")
	@JsonIgnoreProperties("distributeurses")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "nc_commercant", length = 254)
	public String getNcCommercant() {
		return this.ncCommercant;
	}

	public void setNcCommercant(String ncCommercant) {
		this.ncCommercant = ncCommercant;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributeurs")
	@JsonIgnoreProperties({"distributeurs","stockImportation","factureImport"})
	public Set<CommandeImport> getCommandeImports() {
		return this.commandeImports;
	}

	public void setCommandeImports(Set<CommandeImport> commandeImports) {
		this.commandeImports = commandeImports;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "distributeurs")
	@JsonIgnoreProperties("distributeurs")
	public Set<CommandeLocal> getCommandeLocals() {
		return this.commandeLocals;
	}

	public void setCommandeLocals(Set<CommandeLocal> commandeLocals) {
		this.commandeLocals = commandeLocals;
	}

}
