package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * FactureLocal generated by hbm2java
 */
@Entity
@Table(name = "facture_local", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class FactureLocal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idfactLocal;
	private CommandeLocal commandeLocal;
	private Integer prixUnitaire;
	private BigDecimal prixTotal;
	//private Set<CommandeLocal> commandeLocals = new HashSet<CommandeLocal>(0);

	public FactureLocal() {
	}

	public FactureLocal(Long idfactLocal, CommandeLocal commandeLocal) {
		this.idfactLocal = idfactLocal;
		this.commandeLocal = commandeLocal;
	}

	public FactureLocal(Long idfactLocal, CommandeLocal commandeLocal, Integer prixUnitaire, BigDecimal prixTotal
			/*,Set<CommandeLocal> commandeLocals*/) {
		this.idfactLocal = idfactLocal;
		this.commandeLocal = commandeLocal;
		this.prixUnitaire = prixUnitaire;
		this.prixTotal = prixTotal;
		//this.commandeLocals = commandeLocals;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idfact_local", unique = true, nullable = false)
	public Long getIdfactLocal() {
		return this.idfactLocal;
	}

	public void setIdfactLocal(Long idfactImport) {
		this.idfactLocal = idfactImport;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcom_local", nullable = false)
	@JsonIgnoreProperties("factureLocals")
	public CommandeLocal getCommandeLocal() {
		return this.commandeLocal;
	}

	public void setCommandeLocal(CommandeLocal commandeLocal) {
		this.commandeLocal = commandeLocal;
	}

	@Column(name = "prix_unitaire")
	public Integer getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(Integer prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	@Column(name = "prix_total", precision = 131089, scale = 0)
	public BigDecimal getPrixTotal() {
		return this.prixTotal;
	}

	public void setPrixTotal(BigDecimal prixTotal) {
		this.prixTotal = prixTotal;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "factureLocal")
//	@JsonIgnoreProperties("factureLocal")
//	public Set<CommandeLocal> getCommandeLocals() {
//		return this.commandeLocals;
//	}
//
//	public void setCommandeLocals(Set<CommandeLocal> commandeLocals) {
//		this.commandeLocals = commandeLocals;
//	}

}
