package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Gie2 generated by hbm2java
 */
@Entity
@Table(name = "gie2", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Gie2 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idGies2;
	private String nomGie;
	private String siege;
	private String status;
	private Set<Producteurs> producteurses = new HashSet<Producteurs>(0);
	private Set<Importateurs> importateurses = new HashSet<Importateurs>(0);

	public Gie2() {
	}

	public Gie2(Long idGies2) {
		this.idGies2 = idGies2;
	}

	public Gie2(Long idGies2, String nomGie, String siege, String status, Set<Producteurs> producteurses, Set<Importateurs> importateurses) {
		this.idGies2 = idGies2;
		this.nomGie = nomGie;
		this.siege = siege;
		this.status = status;
		this.producteurses = producteurses;
		this.importateurses = importateurses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_gies2", unique = true, nullable = false)
	public Long getIdGies2() {
		return this.idGies2;
	}

	public void setIdGies2(Long idGies2) {
		this.idGies2 = idGies2;
	}

	@Column(name = "nom_gie", length = 254)
	public String getNomGie() {
		return this.nomGie;
	}

	public void setNomGie(String nomGie) {
		this.nomGie = nomGie;
	}

	@Column(name = "siege", length = 254)
	public String getSiege() {
		return this.siege;
	}

	public void setSiege(String siege) {
		this.siege = siege;
	}

	@Column(name = "status", length = 254)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "gie2")
	@JsonIgnoreProperties("gie2")
	public Set<Producteurs> getProducteurses() {
		return this.producteurses;
	}

	public void setProducteurses(Set<Producteurs> producteurses) {
		this.producteurses = producteurses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "gie2")
	@JsonIgnoreProperties("gie2")
	public Set<Importateurs> getImportateurses() {
		return this.importateurses;
	}

	public void setImportateurses(Set<Importateurs> importateurses) {
		this.importateurses = importateurses;
	}

}
