package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Importateurs generated by hbm2java
 */
@Entity
@Table(name = "importateurs", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Importateurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idImport;
	private Utilisateur utilisateur;
	private Gie2 gie2;
	private String ncImport;
	private Set<StockImportation> stockImportations = new HashSet<StockImportation>(0);

	public Importateurs() {
	}

	public Importateurs(Long id, Utilisateur utilisateur) {
		this.idImport = id;
		this.utilisateur = utilisateur;
	}

	public Importateurs(Long id, Utilisateur utilisateur, Gie2 gie2, String ncImport, Set<StockImportation> stockImportations) {
		this.idImport = id;
		this.utilisateur = utilisateur;
		this.gie2 = gie2;
		this.ncImport = ncImport;
		this.stockImportations = stockImportations;
	}
	

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_import")
	public Long getIdImport() {
		return this.idImport;
	}

	public void setIdImport(Long id) {
		this.idImport = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user")
	@JsonIgnoreProperties("importateurses")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gies2")
	@JsonIgnoreProperties("importateurses")
	public Gie2 getGie2() {
		return this.gie2;
	}

	public void setGie2(Gie2 gie2) {
		this.gie2 = gie2;
	}

	@Column(name = "nc_import", length = 254)
	public String getNcImport() {
		return this.ncImport;
	}

	public void setNcImport(String ncImport) {
		this.ncImport = ncImport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importateurs")
	@JsonIgnoreProperties({"importateurses","distributeurses"})
	public Set<StockImportation> getStockImportations() {
		return this.stockImportations;
	}

	public void setStockImportations(Set<StockImportation> stockImportations) {
		this.stockImportations = stockImportations;
	}

}
