package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * OrganisationLongerprofessionel generated by hbm2java
 */
@Entity
@Table(name = "organisation_Interprofessionel", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class OrganisationInterprofessionel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idOrg;
	private String nomOrganisation;
	private String vocation;
	private String status;
	private String siege;
	private String email;
	private BigDecimal telephone;

	public OrganisationInterprofessionel() {
	}

	public OrganisationInterprofessionel(Long idOrg) {
		this.idOrg = idOrg;
	}

	public OrganisationInterprofessionel(Long idOrg, String nomOrganisation, String vocation, String status,
			String siege, String email, BigDecimal telephone) {
		this.idOrg = idOrg;
		this.nomOrganisation = nomOrganisation;
		this.vocation = vocation;
		this.status = status;
		this.siege = siege;
		this.email = email;
		this.telephone = telephone;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_org", unique = true, nullable = false)
	public Long getIdOrg() {
		return this.idOrg;
	}

	public void setIdOrg(Long idOrg) {
		this.idOrg = idOrg;
	}

	@Column(name = "nom_organisation", length = 254)
	public String getNomOrganisation() {
		return this.nomOrganisation;
	}

	public void setNomOrganisation(String nomOrganisation) {
		this.nomOrganisation = nomOrganisation;
	}

	@Column(name = "vocation", length = 254)
	public String getVocation() {
		return this.vocation;
	}

	public void setVocation(String vocation) {
		this.vocation = vocation;
	}

	@Column(name = "status", length = 254)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "siege", length = 254)
	public String getSiege() {
		return this.siege;
	}

	public void setSiege(String siege) {
		this.siege = siege;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", precision = 131089, scale = 0)
	public BigDecimal getTelephone() {
		return this.telephone;
	}

	public void setTelephone(BigDecimal telephone) {
		this.telephone = telephone;
	}

}
