package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Region implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idRegion;
	private String nomRegion;
	private Set<Departement> departements = new HashSet<Departement>(0);

	public Region() {
	}

	public Region(Long idRegion) {
		this.idRegion = idRegion;
	}
	public Region(Long idRegion, String nomRegion) {
		this.idRegion = idRegion;
		this.nomRegion = nomRegion;
		
	}

	public Region(Long idRegion, String nomRegion, Set<Departement> departements) {
		this.idRegion = idRegion;
		this.nomRegion = nomRegion;
		this.departements = departements;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_region", unique = true, nullable = false)
	public Long getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Long idRegion) {
		this.idRegion = idRegion;
	}

	@Column(name = "nom_region", length = 254)
	public String getNomRegion() {
		return this.nomRegion;
	}

	public void setNomRegion(String nomRegion) {
		this.nomRegion = nomRegion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	@JsonIgnoreProperties("region")
	public Set<Departement> getDepartements() {
		return this.departements;
	}

	public void setDepartements(Set<Departement> departements) {
		this.departements = departements;
	}

}
