 package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * StockImportation generated by hbm2java
 */
@Entity
@Table(name = "stock_importation", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class StockImportation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idImportation;
	private Annes annes;
	private Importateurs importateurs;
	private Departement departement;
	private BigDecimal quatite;
	private String qualite;
	private String lieuStock;
	private double prixKg;
	private BigDecimal seuilMax;
	private BigDecimal seuilMin;
	private Set<CommandeImport> commandeImports = new HashSet<CommandeImport>(0);

	public StockImportation() {
	}

	public StockImportation(Long idImportation, Annes annes, Importateurs importateurs, Departement departement) {
		this.idImportation = idImportation;
		this.annes = annes;
		this.importateurs = importateurs;
		this.departement = departement;
	}

	public StockImportation(Long idImportation, Annes annes, Importateurs importateurs, Departement departement,
			BigDecimal quatite, String qualite, String lieuStock, double prixKg, BigDecimal seuilMax,
			BigDecimal seuilMin, Set<CommandeImport> commandeImports) {
		this.idImportation = idImportation;
		this.annes = annes;
		this.importateurs = importateurs;
		this.departement = departement;
		this.quatite = quatite;
		this.qualite = qualite;
		this.lieuStock = lieuStock;
		this.prixKg = prixKg;
		this.seuilMax = seuilMax;
		this.seuilMin = seuilMin;
		this.commandeImports = commandeImports;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_importation", unique = true, nullable = false)
	public Long getIdImportation() {
		return this.idImportation;
	}

	public void setIdImportation(Long idImportation) {
		this.idImportation = idImportation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_annees")
	@JsonIgnoreProperties({"stockImportations", "stockLocals"})
	public Annes getAnnes() {
		return this.annes;
	}

	public void setAnnes(Annes annes) {
		this.annes = annes;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({ @JoinColumn(name = "id_user", referencedColumnName = "id_user"),
			@JoinColumn(name = "id_import", referencedColumnName = "id_import") })
	@JsonIgnoreProperties("stockImportations")
	public Importateurs getImportateurs() {
		return this.importateurs;
	}

	public void setImportateurs(Importateurs importateurs) {
		this.importateurs = importateurs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_departement")
	@JsonIgnoreProperties({"stockImportations","usineTransformations"})
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "quatite", precision = 131089, scale = 0)
	public BigDecimal getQuatite() {
		return this.quatite;
	}

	public void setQuatite(BigDecimal quatite) {
		this.quatite = quatite;
	}

	@Column(name = "qualite", length = 254)
	public String getQualite() {
		return this.qualite;
	}

	public void setQualite(String qualite) {
		this.qualite = qualite;
	}

	@Column(name = "lieu_stock", length = 254)
	public String getLieuStock() {
		return this.lieuStock;
	}

	public void setLieuStock(String lieuStock) {
		this.lieuStock = lieuStock;
	}

	@Column(name = "prix_kg")
	public double getPrixKg() {
		return this.prixKg;
	}

	public void setPrixKg(double prixKg) {
		this.prixKg = prixKg;
	}

	@Column(name = "seuil_max", precision = 131089, scale = 0)
	public BigDecimal getSeuilMax() {
		return this.seuilMax;
	}

	public void setSeuilMax(BigDecimal seuilMax) {
		this.seuilMax = seuilMax;
	}

	@Column(name = "seuil_min", precision = 131089, scale = 0)
	public BigDecimal getSeuilMin() {
		return this.seuilMin;
	}

	public void setSeuilMin(BigDecimal seuilMin) {
		this.seuilMin = seuilMin;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "stockImportation")
	@JsonIgnoreProperties("stockImportation")
	public Set<CommandeImport> getCommandeImports() {
		return this.commandeImports;
	}

	public void setCommandeImports(Set<CommandeImport> commandeImports) {
		this.commandeImports = commandeImports;
	}

}
