package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Transformateurs generated by hbm2java
 */
@Entity
@Table(name = "transformateurs", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Transformateurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idTransf;
	private String nom;
	private String prenom;
	private Set<UsineTransformation> usineTransformations = new HashSet<UsineTransformation>(0);

	public Transformateurs() {
	}

	public Transformateurs(Long idTransf) {
		this.idTransf = idTransf;
	}

	public Transformateurs(Long idTransf, String nom, String prenom, Set<UsineTransformation> usineTransformations) {
		this.idTransf = idTransf;
		this.nom = nom;
		this.prenom = prenom;
		this.usineTransformations = usineTransformations;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_transf", unique = true, nullable = false)
	public Long getIdTransf() {
		return this.idTransf;
	}

	public void setIdTransf(Long idTransf) {
		this.idTransf = idTransf;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transformateurs")
	@JsonIgnoreProperties("transformateurs")
	public Set<UsineTransformation> getUsineTransformations() {
		return this.usineTransformations;
	}

	public void setUsineTransformations(Set<UsineTransformation> usineTransformations) {
		this.usineTransformations = usineTransformations;
	}

}
