package org.sid.entity;
// Generated 1 f�vr. 2019 17:48:23 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * UsineTransformation generated by hbm2java
 */
@Entity
@Table(name = "usine_transformation", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class UsineTransformation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idUsine;
	private Transformateurs transformateurs;
	private Departement departement;
	private String nomUsine;
	private String login;
	private String pwd;
	private String localisation;
	private String email;
	private BigDecimal telephone;
	private Set<StockLocal> stockLocals = new HashSet<StockLocal>(0);
	private Set<Deposerpaddy> deposerpaddies = new HashSet<Deposerpaddy>(0);

	public UsineTransformation() {
	}

	public UsineTransformation(Long idUsine, Transformateurs transformateurs, Departement departement) {
		this.idUsine = idUsine;
		this.transformateurs = transformateurs;
		this.departement = departement;
	}

	public UsineTransformation(Long idUsine, Transformateurs transformateurs, Departement departement, String nomUsine,
			String login, String pwd, String localisation, String email, BigDecimal telephone, Set<StockLocal> stockLocals,
			Set<Deposerpaddy> deposerpaddies) {
		this.idUsine = idUsine;
		this.transformateurs = transformateurs;
		this.departement = departement;
		this.nomUsine = nomUsine;
		this.login = login;
		this.pwd = pwd;
		this.localisation = localisation;
		this.email = email;
		this.telephone = telephone;
		this.stockLocals = stockLocals;
		this.deposerpaddies = deposerpaddies;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_usine", unique = true, nullable = false)
	public Long getIdUsine() {
		return this.idUsine;
	}

	public void setIdUsine(Long idUsine) {
		this.idUsine = idUsine;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_transf")
	@JsonIgnoreProperties("usineTransformations")
	public Transformateurs getTransformateurs() {
		return this.transformateurs;
	}

	public void setTransformateurs(Transformateurs transformateurs) {
		this.transformateurs = transformateurs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_departement")
	@JsonIgnoreProperties({"usineTransformations","stockImportations"})
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "nom_usine", length = 254)
	public String getNomUsine() {
		return this.nomUsine;
	}

	public void setNomUsine(String nomUsine) {
		this.nomUsine = nomUsine;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "pwd", length = 254)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "localisation", length = 254)
	public String getLocalisation() {
		return this.localisation;
	}

	public void setLocalisation(String localisation) {
		this.localisation = localisation;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", precision = 131089, scale = 0)
	public BigDecimal getTelephone() {
		return this.telephone;
	}

	public void setTelephone(BigDecimal telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "usineTransformation")
	@JsonIgnoreProperties("usineTransformation")
	public Set<StockLocal> getStockLocals() {
		return this.stockLocals;
	}

	public void setStockLocals(Set<StockLocal> stockLocals) {
		this.stockLocals = stockLocals;
	}

	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.EAGER, mappedBy = "usineTransformation")
	@JsonIgnoreProperties(value={"usineTransformation"}, allowSetters = true)
	public Set<Deposerpaddy> getDeposerpaddies() {
		return this.deposerpaddies;
	}

	public void setDeposerpaddies(Set<Deposerpaddy> deposerpaddies) {
		this.deposerpaddies = deposerpaddies;
	}

}
